kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ocr.fullname" . }}-easyocr
  labels:
    {{- include "ocr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ocr.fullname" . }}-csv
  labels:
    {{- include "ocr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
